#  Copyright (c) 2018 5GTANGO, Paderborn University
# ALL RIGHTS RESERVED.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Neither the name of the SONATA-NFV, 5GTANGO, Paderborn University
# nor the names of its contributors may be used to endorse or promote
# products derived from this software without specific prior written
# permission.
#
# This work has also been performed in the framework of the 5GTANGO project,
# funded by the European Commission under Grant number 761493 through
# the Horizon 2020 and 5G-PPP programmes. The authors would like to
# acknowledge the contributions of their colleagues of the SONATA
# partner consortium (www.5gtango.eu).---


apiVersion: apps/v1
kind: Service
metadata:
  name: usecase3
  labels:
    pilot: sm
spec:
  selector:
    # must match the labels of the template
    matchLabels:
      pilot: sm
    type: LoadBalancer
    ports:
      - name: squid
        port: 3128 
      - name: openvpn
        port: 1194
      - name: skype1
        port: 443
        protocol: TCP
      - name: skype2
        port: 3478-3481
        protocol: UDP
      - name: skype3
        port: 50000-60000
        protocol: UDP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usecase3
  labels:
    pilot: sm
  spec:
    selector:
      matchLabels:
        pilot: sm
    template:
      metadata:
        labels:
          pilot: sm
      spec:
        containers:
        - name: glasses-connector
          image: sonatanfv/squidproxy:k8s
          imagePullPolicy: Always
          ports:
          - containerPort: 1194
            name: openvpn
          - containerPort: 3128
            name: squid
          - containerPort: 443
            name: skype1
          - containerPort: 3478-3481
            name: skype2
          - containerPort: 50000-60000
            name: skype3
          parameters:
            capabilities:
            - NET_ADMIN
            - SYS_ADMIN
